# Generated by Django 3.2.8 on 2021-10-28 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
